name: open_whats_app_numbers
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_riverpod: ^2.5.3
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.10+1
  form_validator: ^2.1.1
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^8.0.0
  json_annotation: ^4.9.0
  objectbox: ^4.0.2
  objectbox_flutter_libs: any
  path: ^1.9.0
  path_provider: ^2.1.4
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0

objectbox:
  output_dir:
    lib: objectbox

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  objectbox_generator: any
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/app_icons/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
